enketo-core: fix getter-only number-input properties
Before this fix, the browser console error shows info such as:
TypeError: Cannot set property x of #<Object> which has only a getter

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Getter_only